#export INSTALLPATH=/home/alferezn/Dropbox/dNami/src
#export INSTALLPATH=/Users/etouber/Dropbox/RESEARCH/Projects/CODES/dNami/src
#export  INSTALLPATH=/home/nalferez/Dropbox/dNami/src
export  INSTALLPATH=/mnt/Dropbox/dNami_git/dNamiDynFluid/src/
export  PYTHONPATH=$PYTHONPATH:$INSTALLPATH/src_py
export  PYTHONPATH=$PYTHONPATH:$INSTALLPATH/pymod
export  PYTHONPATH=$PYTHONPATH:$INSTALLPATH/generate/
export  PYTHONPATH=$PYTHONPATH:/mnt/Dropbox/dNami_git/dNami/devTests/2d/
export  PYTHONPATH=$PYTHONPATH:/mnt/Dropbox/dNami_git/dNami/src/generate/archive/forConsLaw/
#export  KMP_AFFINITY='verbose,granularity=fine,compact,1,0'
export  KMP_AFFINITY='verbose,granularity=fine,proclist=[10,11,12,13,14,15,16,17,18,19,20,0,1,2,3,4,5,6,7,8,9],explicit'
